In [1]:
import numpy as np 
import pandas as pd

In [2]:
data= np.array([[1,2,3],
                [4,5,6],
                [7,9,8]])
print((data+5))

[[ 6  7  8]
 [ 9 10 11]
 [12 14 13]]


# start numpy basic

In [3]:
#a = np.arange(2,21,2)


In [4]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [5]:
print("shape",a.shape)
print('dimnsion' ,a.ndim)
print("siz",a.size)

shape (3, 3)
dimnsion 2
siz 9


In [6]:
#slicing
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a[1,2]


6

In [7]:
data = np.arange(10*10).reshape(10,10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
data= np.array([[1,2,3],
                [4,5,6],
                [7,9,8]])

In [9]:
data % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 1, 0]], dtype=int32)

In [10]:
data=np.arange(1,10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
data=np.arange(1,10,2)
data


array([1, 3, 5, 7, 9])

In [12]:
data=np.arange(1,10,2)

In [13]:
data = np.arange(10*10).reshape(10,10)# .reshape(num_row, num_col)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [14]:
data[5: ,5: ] = data[5: ,5: ]
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
data[3,9]

39

In [16]:
data = np.arange(12*12).reshape(12,12)# .reshape(num_row, num_col)
#     rows ,  cols
data

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143]])

In [17]:
data[2:-2,2:-2]

array([[ 26,  27,  28,  29,  30,  31,  32,  33],
       [ 38,  39,  40,  41,  42,  43,  44,  45],
       [ 50,  51,  52,  53,  54,  55,  56,  57],
       [ 62,  63,  64,  65,  66,  67,  68,  69],
       [ 74,  75,  76,  77,  78,  79,  80,  81],
       [ 86,  87,  88,  89,  90,  91,  92,  93],
       [ 98,  99, 100, 101, 102, 103, 104, 105],
       [110, 111, 112, 113, 114, 115, 116, 117]])

In [18]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(20, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones(6, dtype=np.int)


C:\Users\samma\AppData\Local\Temp\ipykernel_12080\538504265.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones(6, dtype=np.int)


array([1, 1, 1, 1, 1, 1])

In [21]:
data.shape

(12, 12)

In [22]:
np.ones(data.shape, dtype=np.int)


C:\Users\samma\AppData\Local\Temp\ipykernel_12080\3627138763.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones(data.shape, dtype=np.int)


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [23]:
np.zeros_like(data)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.ones_like(data)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [25]:
np.empty(12)

array([1.12756280e-311, 3.16202013e-322, 0.00000000e+000, 0.00000000e+000,
       1.03977794e-312, 2.90315669e-057, 4.28173385e-037, 1.40416055e+165,
       2.67825814e+184, 4.01346174e-057, 1.11619197e-046, 9.39444468e+165])

In [26]:
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
data = np.arange(63,93)
data

array([63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92])

In [28]:
data = np.array([chr(i) for i in range(63,80)], dtype=str)
data

array(['?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
       'L', 'M', 'N', 'O'], dtype='<U1')

In [29]:
bank_data =np.array(["samad","faisal","afnan","hamza","saad"])

In [30]:
stat_bank_data=np.array(["ali",'Faisal',"saad","tahir","nayab"])

In [31]:
np.in1d(bank_data,stat_bank_data)

array([False, False, False, False,  True])

In [32]:
np.intersect1d(bank_data,stat_bank_data)

array(['saad'], dtype='<U6')

In [33]:
np.union1d(bank_data,stat_bank_data)

array(['Faisal', 'afnan', 'ali', 'faisal', 'hamza', 'nayab', 'saad',
       'samad', 'tahir'], dtype='<U6')

In [34]:
data=np.array(list(map(str.lower,data)))
data

array(['?', '@', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k',
       'l', 'm', 'n', 'o'], dtype='<U1')

In [35]:
bank_data=np.array(list(map(str.upper,bank_data)))
bank_data

array(['SAMAD', 'FAISAL', 'AFNAN', 'HAMZA', 'SAAD'], dtype='<U6')

In [36]:
np.intersect1d(bank_data,stat_bank_data)

array([], dtype='<U6')

# handle issue like space, lower and uper case with function


In [37]:
bank_data =np.array(["   samad","faisal","  afnan","hamza","saad  "])

In [38]:
np.intersect1d(bank_data,stat_bank_data)

array([], dtype='<U8')

In [47]:
def preprocessing (txt):
    txt=str(txt)
    txt=txt.lower()
    txt=txt.strip()
    return txt
 
 

In [42]:
preprocessing('pakistan zindabad  ') 

'pakistan zindabad'

In [48]:
bank_data=np.array(list(map( preprocessing,bank_data)))

In [54]:
bank_data

array(['SAMAD', 'FAISAL', 'AFNAN', 'HAMZA', 'SAAD'], dtype='<U6')

In [50]:
def preprocessing2 (txt):
    txt=str(txt)
    txt=txt.upper()
    txt=txt.strip()
    return txt
 

In [51]:
bank_data=np.array(list(map( preprocessing2,bank_data)))

In [52]:
bank_data

array(['SAMAD', 'FAISAL', 'AFNAN', 'HAMZA', 'SAAD'], dtype='<U6')

# Slicing and Indexing

In [57]:
data5=np.arange(1,100)
data5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
print(data5[1:5])

[]
